// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdkButton: typeof import('./src/components/AdkButton/AdkButton.vue')['default']
    AdkEmpty: typeof import('./src/components/AdkEmpty/AdkEmpty.vue')['default']
    AnimeCard: typeof import('./src/components/Bangumimini/components/AnimeCard.vue')['default']
    ArticleItem: typeof import('./src/components/ArticleItem/ArticleItem.vue')['default']
    Bangumimini: typeof import('./src/components/Bangumimini/Bangumimini.vue')['default']
    Carousel: typeof import('./src/components/Carousel/Carousel.vue')['default']
    CommentItem: typeof import('./src/components/CommentItem/CommentItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    FooterItem: typeof import('./src/components/Footer/FooterItem.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LoadingAnime: typeof import('./src/components/LoadingAnime/LoadingAnime.vue')['default']
    Logo: typeof import('./src/components/TopNavBar/components/Logo.vue')['default']
    MessageFrom: typeof import('./src/components/CommentItem/MessageFrom.vue')['default']
    MyElimage: typeof import('./src/components/MyElimage/MyElimage.vue')['default']
    PcMenu: typeof import('./src/components/TopNavBar/components/PcMenu.vue')['default']
    RightInfoBox: typeof import('./src/components/TopNavBar/components/RightInfoBox.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    TopNavBar: typeof import('./src/components/TopNavBar/TopNavBar.vue')['default']
  }
}

export { }
